# Generated by Django 5.1.4 on 2025-02-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [

    ]
